#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Feb 23 12:38:41 PST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim i2c_master_tb_behav -key {Behavioral:sim_1:Functional:i2c_master_tb} -tclbatch i2c_master_tb.tcl -view /home/dtorres/Documents/work/PID_maze_navigator/vivado/pwm/i2c_master_tb_behav.wcfg -log simulate.log"
xsim i2c_master_tb_behav -key {Behavioral:sim_1:Functional:i2c_master_tb} -tclbatch i2c_master_tb.tcl -view /home/dtorres/Documents/work/PID_maze_navigator/vivado/pwm/i2c_master_tb_behav.wcfg -log simulate.log

